# Generated by Django 5.1.1 on 2024-10-21 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=250)),
                ('industry', models.CharField(choices=[('agriculture', 'Agriculture'), ('aerospace', 'Aerospace'), ('automotive', 'Automotive'), ('chemicals', 'Chemicals'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('information_technology', 'Information Technology'), ('cybersecurity', 'Cybersecurity'), ('biotechnology', 'Biotechnology'), ('healthcare', 'Healthcare'), ('pharmaceuticals', 'Pharmaceuticals'), ('medical_devices', 'Medical Devices'), ('banking_finance', 'Banking and Finance'), ('insurance', 'Insurance'), ('real_estate', 'Real Estate'), ('retail', 'Retail'), ('food_beverage', 'Food and Beverage'), ('hospitality', 'Hospitality'), ('energy', 'Energy and Renewable Energy'), ('environmental_services', 'Environmental Services and Sustainability'), ('media', 'Media'), ('entertainment', 'Entertainment'), ('gaming', 'Gaming'), ('sports', 'Sports'), ('transportation', 'Transportation'), ('logistics', 'Logistics'), ('travel_tourism', 'Travel and Tourism'), ('education', 'Education'), ('others', 'Others')], default='agriculture', max_length=50)),
                ('type_of_service', models.CharField(choices=[('PM', 'Project Management'), ('RP', 'Research and Policy Development'), ('DA', 'Data Analysis and Management'), ('ME', 'Monitoring and Evaluation'), ('SE', 'Stakeholder Engagement and Advocacy'), ('CB', 'Capacity Building and Training'), ('OT', 'Others')], default='PM', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-type_of_service'], name='business_bu_type_of_0a440a_idx')],
            },
        ),
    ]
