# Generated by Django 5.1.1 on 2024-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='project_description',
            field=models.TextField(default='A short description of your project', max_length=1000),
        ),
    ]
