# Generated by Django 5.1.1 on 2024-10-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_business_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='project_description',
            field=models.TextField(default='Describe in few words...', max_length=5000),
        ),
    ]
