# Generated by Django 5.1.1 on 2024-10-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[('no', '-------'), ('agriculture', 'Agriculture'), ('aerospace', 'Aerospace'), ('automotive', 'Automotive'), ('chemicals', 'Chemicals'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('information_technology', 'Information Technology'), ('cybersecurity', 'Cybersecurity'), ('biotechnology', 'Biotechnology'), ('healthcare', 'Healthcare'), ('pharmaceuticals', 'Pharmaceuticals'), ('medical_devices', 'Medical Devices'), ('banking_finance', 'Banking and Finance'), ('insurance', 'Insurance'), ('real_estate', 'Real Estate'), ('retail', 'Retail'), ('food_beverage', 'Food and Beverage'), ('hospitality', 'Hospitality'), ('energy', 'Energy and Renewable Energy'), ('environmental_services', 'Environmental Services and Sustainability'), ('media', 'Media'), ('entertainment', 'Entertainment'), ('gaming', 'Gaming'), ('sports', 'Sports'), ('transportation', 'Transportation'), ('logistics', 'Logistics'), ('travel_tourism', 'Travel and Tourism'), ('education', 'Education'), ('others', 'Others')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='type_of_service',
            field=models.CharField(choices=[('NO', '-------'), ('PM', 'Project Management'), ('RP', 'Research and Policy Development'), ('DA', 'Data Analysis and Management'), ('ME', 'Monitoring and Evaluation'), ('SE', 'Stakeholder Engagement and Advocacy'), ('CB', 'Capacity Building and Training'), ('OT', 'Others')], default='NO', max_length=2),
        ),
    ]
