# Generated by Django 5.1.1 on 2024-10-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_business_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type_of_service',
            field=models.CharField(choices=[('NO', '-------'), ('CP', 'Customer Preference and Sentiment Analysis'), ('PP', 'Price/Stock Prediction and Fluctuation Analysis'), ('HR', 'Human Resources Analysis'), ('BP', 'Business Proposal Writing'), ('OT', 'Other Business Analytics Services')], default='NO', max_length=2),
        ),
    ]
