# Generated by Django 5.1.1 on 2024-10-22 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(choices=[('DP', 'Diploma'), ('UG', 'Undergraduate'), ('GR', 'Graduate'), ('PG', 'Post-Graduate'), ('DR', 'Doctoral'), ('PD', 'Postdoctoral')], default='UG', max_length=2)),
                ('name_of_institution', models.CharField(max_length=500)),
                ('type_of_service', models.CharField(choices=[('full_project', 'Full Project Dissertation/Thesis'), ('proposal', 'Project Proposal'), ('data_analysis', 'Data Analysis and Interpretation'), ('other', 'Other Academic Services')], default='full_project', max_length=50)),
                ('project_title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-type_of_service'], name='academics_a_type_of_aca7ee_idx')],
            },
        ),
    ]
