# Generated by Django 5.1.1 on 2024-10-22 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='academic_level',
            field=models.CharField(choices=[('NO', '-------'), ('DP', 'Diploma'), ('UG', 'Undergraduate'), ('GR', 'Graduate'), ('PG', 'Post-Graduate'), ('DR', 'Doctoral'), ('PD', 'Postdoctoral')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='academic',
            name='type_of_service',
            field=models.CharField(choices=[('no', '-------'), ('full_project', 'Full Project Dissertation/Thesis'), ('proposal', 'Project Proposal'), ('data_analysis', 'Data Analysis and Interpretation'), ('other', 'Other Academic Services')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='academic',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to=settings.AUTH_USER_MODEL),
        ),
    ]
